auto:             true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            creatstar.com
url:              http://creatstar.com
author:
    name:         creatstar
    weibo:        weibo.com/creatstar
description:      "Winnie and Creatstar\'s Blog"
author_info:      <a href="http://creatstar.com/about">creatstar</a>

copyright:
    - Design by <a href="http://creatstar.com/about" title="creatstar" target="_blank">creatstar</a> &copy; Copyright 2012
